---
- name: Replace strings in files on app servers
  hosts: all
  become: true
  tasks:
    - name: Replace string in blog.txt on app server 1
      replace:
        path: /opt/dba/blog.txt
        regexp: 'xFusionCorp'
        replace: 'Nautilus'
      when: inventory_hostname == "stapp01"

    - name: Replace string in story.txt on app server 2
      replace:
        path: /opt/dba/story.txt
        regexp: 'Nautilus'
        replace: 'KodeKloud'
      when: inventory_hostname == "stapp02"

    - name: Replace string in media.txt on app server 3
      replace:
        path: /opt/dba/media.txt
        regexp: 'KodeKloud'
        replace: 'xFusionCorp Industries'
      when: inventory_hostname == "stapp03"