---
- name: Configure app server 1
  hosts: stapp01
  become: yes
  tasks:
    - name: Create directory /opt/devops if it doesn't exist
      file:
        path: /opt/devops
        state: directory
        mode: '0755'

    - name: Create empty file blog.txt
      file:
        path: /opt/devops/blog.txt
        state: touch
        owner: tony
        group: tony
        mode: '0644'

    - name: Create symbolic link from /opt/devops to /var/www/html
      file:
        src: /opt/devops
        dest: /var/www/html
        state: link

- name: Configure app server 2
  hosts: stapp02
  become: yes
  tasks:
    - name: Create directory /opt/devops if it doesn't exist
      file:
        path: /opt/devops
        state: directory
        mode: '0755'

    - name: Create empty file story.txt
      file:
        path: /opt/devops/story.txt
        state: touch
        owner: steve
        group: steve
        mode: '0644'

    - name: Create symbolic link from /opt/devops to /var/www/html
      file:
        src: /opt/devops
        dest: /var/www/html
        state: link

- name: Configure app server 3
  hosts: stapp03
  become: yes
  tasks:
    - name: Create directory /opt/devops if it doesn't exist
      file:
        path: /opt/devops
        state: directory
        mode: '0755'

    - name: Create empty file media.txt
      file:
        path: /opt/devops/media.txt
        state: touch
        owner: banner
        group: banner
        mode: '0644'

    - name: Create symbolic link from /opt/devops to /var/www/html
      file:
        src: /opt/devops
        dest: /var/www/html
        state: link