---
- name: Configure app server 1
  hosts: stapp01
  become: yes
  tasks:
    - name: Create /opt/itadmin directory
      file:
        path: /opt/itadmin
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create empty file blog.txt
      file:
        path: /opt/itadmin/blog.txt
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Set ACL for group tony on blog.txt
      acl:
        path: /opt/itadmin/blog.txt
        entity: tony
        etype: group
        permissions: r
        state: present

- name: Configure app server 2
  hosts: stapp02
  become: yes
  tasks:
    - name: Create /opt/itadmin directory
      file:
        path: /opt/itadmin
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create empty file story.txt
      file:
        path: /opt/itadmin/story.txt
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Set ACL for user steve on story.txt
      acl:
        path: /opt/itadmin/story.txt
        entity: steve
        etype: user
        permissions: rw
        state: present

- name: Configure app server 3
  hosts: stapp03
  become: yes
  tasks:
    - name: Create /opt/itadmin directory
      file:
        path: /opt/itadmin
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create empty file media.txt
      file:
        path: /opt/itadmin/media.txt
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Set ACL for group banner on media.txt
      acl:
        path: /opt/itadmin/media.txt
        entity: banner
        etype: group
        permissions: rw
        state: present